kapture-setup checks

diff --git a/bin/kapture-setup b/bin/kapture-setup
--- a/bin/kapture-setup
+++ b/bin/kapture-setup
@@ -1,6 +1,18 @@
 #!/bin/bash
+set -e
 
 BASE_PATH=/var/kapture/ansible
 ANSIBLE_CONFIG="$BASE_PATH/ansible.cfg"
+
+if ! which pip > /dev/null; then
+  echo "pip required, please install via: "
+  echo "sudo apt-get install python-pip -y"
+  exit 1
+fi
+
+if ! which ansible > /dev/null; then
+  echo "ansible not installed, attempting to install (you may need to run this with sudo)"
+  pip install -U ansible
+fi
 
 ansible-playbook -c local -i 'localhost,' $BASE_PATH/kapture.yml
